apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: adminer
  labels:
    app: adminer
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:4.8.1  
          resources:
            limits:
              memory: "200Mi"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: adminer-service
spec:
  type: NodePort
  selector:
    app: adminer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002