apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
spec:
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:
      labels:
        app: code-server
    spec:
      containers:
      - name: code-server
        image: linuxserver/code-server:4.9.1
        env:
          - name:  PASSWORD
            valueFrom:
              secretKeyRef:
                name:  code-server-secret
                key:  PASSWORD
          - name:  SUDO_PASSWORD
            valueFrom:
              secretKeyRef:
                name:  code-server-secret
                key:  SUDO_PASSWORD
          - name:  env
            valueFrom:
              configMapRef:
                key: code-server-env
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 8443
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: code-server
  namespace: luckytree
spec:
  selector:
    app: code-server
  type: ClusterIP
  ports:
  - name: code-server
    protocol: TCP
    port: 8443
    targetPort: 8443
---
# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
  name: code-server-ingress-ssl
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - code.c0dewave.com
    secretName: secret-https
  rules:
  - host: code.c0dewave.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: code-server
            port:
              number: 8443