apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:  
      securityContext:
        runAsUser: 104
      containers:
        - name: grafana
          image: grafana/grafana:9.2.6
          volumeMounts:
          - mountPath: "/var/lib/grafana"
            name: grafana-lib
          - mountPath: "/etc/grafana"
            name: grafana-conf
          - mountPath: "/var/log/grafana"
            name: grafana-log
          resources:
            limits:
              memory: "400Mi"
          ports:
            - containerPort: 3000
      volumes:
      - name : grafana-conf
        hostPath:
          path: /disk01/grafana_data/grafana-conf
          type: DirectoryOrCreate
      - name : grafana-lib
        hostPath:
          path: /disk01/grafana_data/grafana-lib
          type: DirectoryOrCreate
      - name : grafana-log
        hostPath:
          path: /disk01/grafana_data/grafana-log
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30003