apiVersion: v1
kind: Service
metadata:
  name: harbor-service
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: v1
kind: Endpoints
metadata:
  name: harbor-service
subsets:
  - addresses:
      - ip: 192.168.0.14 # 외부 웹 서버 IP 주소 
    ports:
      - name: https
        port: 443
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/backend-protocol: HTTPS
      nginx.org/client-max-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
  name: harbor-ingress
spec:
  tls:
  - hosts:
    - harbor.c0dewave.com
    secretName: secret-https
  rules:
  - host: harbor.c0dewave.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harbor-service
            port:
              number: 443