apiVersion: v1
kind: Service
metadata:
  name: harbor-service
spec:
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: harbor-service-1 # by convention, use the name of the Service
                     # as a prefix for the name of the EndpointSlice
  labels:
    # You should set the "kubernetes.io/service-name" label.
    # Set its value to match the name of the Service
    kubernetes.io/service-name: harbor-service
addressType: IPv4
ports:
  - name: 'https' # empty because port 9376 is not assigned as a well-known
                 # port (by IANA)
    protocol: TCP
    port: 443
endpoints:
  - addresses:
      - "192.168.0.14"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: "nginx"
  name: grafana-ingress
spec:
  tls:
  - hosts:
    - harbor.c0dewave.com
    secretName: secret-https
  rules:
  - host: harbor.c0dewave.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: harbor-service
            port:
              number: 443