apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rabbitmq
  labels:
    name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq
  template:
    metadata:
      name: rabbitmq
      labels:
        name: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.9.26-management
          ports:
            - containerPort: 15672
            - containerPort: 5672
          envFrom:
          - configMapRef:
              name: rabbitmq-config
          env:
            - name:  rabbitmq secret
              valueFrom:
                secretKeyRef:
                  name:  rabbitmq-pass-secret
                  key:  RABBITMQ_DEFAULT_PASS
          resources:
            limits:
              memory: "2Gi"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  RABBITMQ_DEFAULT_USER: luckytree
 
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  type: NodePort
  selector:
    name: rabbitmq
  ports:
  - port: 15672
    targetPort: 15672
    nodePort: 30020