apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: docker-registry
  labels:
    name: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      name: docker-registry
  template:
    metadata:
      name: docker-registry
      labels:
        name: docker-registry
    spec:
      containers:
        - name: docker-registry-web
          image: hyper/docker-registry-web:v0.1.2
          ports:
            - containerPort: 8080
          envFrom:
          - configMapRef:
              name: docker-registry-config
          resources:
            limits:
              memory: "2Gi"
        - name: docker-registry
          image: registry:2.8.1
          volumeMounts:
          - mountPath: "/var/lib/registry"
            name: regstry-data
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "500Mi"
      volumes:
      - name : regstry-data
        hostPath:
          path: /disk01/docker-regstry
          type: DirectoryOrCreate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry-config
data:
  REGISTRY_NAME: luckytree:5000
  REGISTRY_URL: http://localhost:5000/v2
--- 
  apiVersion: v1
  kind: Service
  metadata:
    name: docker-registry-web
  spec:
    type: NodePort
    selector:
      name: docker-registry
    ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30015
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  selector:
    app: docker-registry
  ports:
  - port: 5000
    targetPort: 5000

      
  