apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: teamcity
  template:
    metadata:
      labels:
        app: teamcity
    spec:
      containers:
      - name: teamcity
        image: jetbrains/teamcity-server:2022.10
        resources:
          limits:
            memory: "2Gi"
        volumeMounts:
        - mountPath: "/data/teamcity_server/datadir"
          name: teamcity-data-volume
        - mountPath: "/opt/teamcity/logs"
          name: teamcity-log-volume
        ports:
        - containerPort: 8111
        - containerPort: 8112
      volumes:
      - name: teamcity-data-volume
        persistentVolumeClaim:
          claimName: teamcity-data-pvc
      - name: teamcity-log-volume
        persistentVolumeClaim:
          claimName: teamcity-log-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-data-pv
spec:
  capacity:
    storage: 51Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /disk01/teamcity/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - luckytree-study
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-data-pvc
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  volumeName: teamcity-data-pv
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-log-pv
spec:
  capacity:
    storage: 51Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /disk01/teamcity/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - luckytree-study
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-log-pvc
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  volumeName: teamcity-log-pv
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity
spec:
  type: NodePort
  selector:
    app: teamcity
  ports:
  - port: 8111
    targetPort: 8111
    nodePort: 30012
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-ssl
spec:
  type: NodePort
  selector:
    app: teamcity
  ports:
  - port: 8112
    targetPort: 8112
    nodePort: 30025
---
# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
      nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
  name: teamcity-ingress-ssl
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - teamcity.c0dewave.com
    secretName: secret-https
  rules:
  - host: teamcity.c0dewave.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teamcity
            port:
              number: 8111
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: oauth2-proxy
  template:
    metadata:
      labels:
        k8s-app: oauth2-proxy
    spec:
      containers:
      - args:
        - --provider=github
        - --github-org=lucky-treee
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --cookie-secure=false
        env:
          - name:  OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name:  git-teamcity-secret
                key:  OAUTH2_PROXY_CLIENT_ID
          - name:  OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name:  git-teamcity-secret
                key:  OAUTH2_PROXY_CLIENT_SECRET
          - name:  OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                name:  git-teamcity-secret
                key:  OAUTH2_PROXY_COOKIE_SECRET
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
        imagePullPolicy: Always
        name: oauth2-proxy
        ports:
        - containerPort: 4180
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: oauth2-proxy
  name: oauth2-proxy
spec:
  ports:
  - name: http
    port: 4180
    protocol: TCP
    targetPort: 4180
  selector:
    k8s-app: oauth2-proxy
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-proxy
spec:
  ingressClassName: nginx
  rules:
  - host: teamcity.c0dewave.com
    http:
      paths:
      - path: /oauth2
        pathType: Prefix
        backend:
          service:
            name: oauth2-proxy
            port:
              number: 4180
  tls:
  - hosts:
    - teamcity.c0dewave.com
    secretName: secret-https