# apiVersion: apps/v1
# kind: ReplicaSet
# metadata:
#   name: teamcity-agnet
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: teamcity-agnet
#   template:
#     metadata:
#       name: teamcity-agnet
#       labels:
#         app: teamcity-agnet
#     spec:
#       containers:
#         - name: teamcity-agnet
#           image: localhost:30016/luckytree-teamcity-agent:0.4
#           securityContext:
#             allowPrivilegeEscalation: true
#           envFrom:
#           - configMapRef:
#               name: teamcity-agnet-config
#           resources:
#             limits:
#               memory: "1.5Gi"
#           volumeMounts:
#           - mountPath: /var/run/docker.sock
#             name: docker-socket
#           - mountPath: /opt/buildagent/temp
#             name: opt-folder-temp
#           - mountPath: /opt/buildagent/work
#             name: opt-folder-work
#           # - mountPath: /opt/buildagent/lib
#           #   name: opt-folder-lib
#           - mountPath: /opt/buildagent/tools
#             name: opt-folder-tools
#           - mountPath: /opt/buildagent/plugins
#             name: opt-folder-plugins
#           - mountPath: /opt/buildagent/system
#             name: opt-folder-system
#       volumes:
#       - name : docker-socket
#         hostPath:
#           path: /var/run/docker.sock
#           type: Socket
#       - name : opt-folder-temp
#         hostPath:
#           path: /opt/buildagent/temp
#           type: DirectoryOrCreate
#       - name : opt-folder-work
#         hostPath:
#           path: /opt/buildagent/work
#           type: DirectoryOrCreate
#       # - name : opt-folder-lib
#       #   hostPath:
#       #     path: /opt/buildagent/lib
#       #     type: DirectoryOrCreate
#       - name : opt-folder-tools
#         hostPath:
#           path: /opt/buildagent/tools
#           type: DirectoryOrCreate
#       - name : opt-folder-plugins
#         hostPath:
#           path: /opt/buildagent/plugins
#           type: DirectoryOrCreate
#       - name : opt-folder-system
#         hostPath:
#           path: /opt/buildagent/system
#           type: DirectoryOrCreate
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: teamcity-agnet-config
data:
  name: "luckytree-teamcity-agent"
  JAVA_HOME: "/opt/java/openjdk"
  JRE_HOME: "/opt/java/jdk-11.0.2"
  DOCKER_IN_DOCKER: start
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: teamcity-agnet
spec:
  selector:
    matchLabels:
      app: teamcity-agnet
  serviceName: teamcity-agnet-service
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: teamcity-agnet
    spec:
      nodeSelector:
        kubernetes.io/hostname: luckytree-study
      containers:
      - name: teamcity-agnet
        image: localhost:30016/luckytree-teamcity-agent:0.4
        securityContext:
            allowPrivilegeEscalation: true
        envFrom:
          - configMapRef:
              name: teamcity-agnet-config
        resources:
          limits:
            memory: "1.5Gi"
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-socket
          - mountPath: /opt/buildagent/temp
            name: opt-folder-temp
          - mountPath: /opt/buildagent/work
            name: opt-folder-work
          - mountPath: /opt/buildagent/tools
            name: opt-folder-tools
          - mountPath: /opt/buildagent/plugins
            name: opt-folder-plugins
          - mountPath: /opt/buildagent/system
            name: opt-folder-system
      volumes:
      - name : docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name : opt-folder-temp
        hostPath:
          path: /opt/buildagent/temp
          type: DirectoryOrCreate
      - name : opt-folder-work
        hostPath:
          path: /opt/buildagent/work
          type: DirectoryOrCreate
      - name : opt-folder-tools
        hostPath:
          path: /opt/buildagent/tools
          type: DirectoryOrCreate
      - name : opt-folder-plugins
        hostPath:
          path: /opt/buildagent/plugins
          type: DirectoryOrCreate
      - name : opt-folder-system
        hostPath:
          path: /opt/buildagent/system
          type: DirectoryOrCreate