apiVersion: apps/v1
kind: Deployment
metadata:
  name: teamcity
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: teamcity
  template:
    metadata:
      labels:
        app: teamcity
    spec:
      containers:
      - name: teamcity
        image: jetbrains/teamcity-server:2022.10
        resources:
          limits:
            memory: "2Gi"
        volumeMounts:
        - mountPath: "/data/teamcity_server/datadir"
          name: teamcity-data-volume
        - mountPath: "/opt/teamcity/logs"
          name: teamcity-log-volume
        ports:
        - containerPort: 8111
        - containerPort: 8112
      volumes:
      - name: teamcity-data-volume
        persistentVolumeClaim:
          claimName: teamcity-data-pvc
      - name: teamcity-log-volume
        persistentVolumeClaim:
          claimName: teamcity-log-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-data-pv
spec:
  capacity:
    storage: 51Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /disk01/teamcity/data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - luckytree-study
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-data-pvc
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  volumeName: teamcity-data-pv
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: teamcity-log-pv
spec:
  capacity:
    storage: 51Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /disk01/teamcity/logs
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - luckytree-study
  
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teamcity-log-pvc
spec:
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Gi
  volumeName: teamcity-log-pv
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity
spec:
  type: NodePort
  selector:
    app: teamcity
  ports:
  - port: 8111
    targetPort: 8111
    nodePort: 30012
---
apiVersion: v1
kind: Service
metadata:
  name: teamcity-ssl
spec:
  type: NodePort
  selector:
    app: teamcity
  ports:
  - port: 8112
    targetPort: 8112
    nodePort: 30025
---
# https://kubernetes.io/docs/concepts/services-networking/ingress/
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teamcity-ingress-ssl
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - teamcity.c0dewave.com
    secretName: secret-https
  rules:
  - host: teamcity.c0dewave.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: teamcity
            port:
              number: 8111
---
